apiVersion: v1
kind: Service
metadata:
  name: pact-broker-service
  labels:
    app: pact-broker
spec:
  type: NodePort
  selector:
    app: pact-broker
  ports:
    - protocol: TCP
      port: 9393
      targetPort: 9393
